### ISSUE TITLE
Reminder to write down username needed

### ISSUE THREAD

**Issue by gryter** [steemit/faucet#298] opened 2018-04-15 22:57 UTC
**Issue:** Users forget their username between the time they registered and the time the account was activated.

**In:** 
faucet/src/locales/en.json
"email_verified": "Your email address has been verified.",
**Suggested replacement:**
"Your email address has been verified. Write down your username so you don't forget it!",

**Reasoning:**
The username is not included in any registration communications. (This is a standard security feature to safeguard the user in case their email account is hacked or monitored.)

**Proposed Solution:** Add a message to users to write down their chosen username.  The username is right on the same screen as follows: 

https://steemitimages.com/DQmcmpjgrfyrQkcPAwfd5QnLDVRpGm8JJQL5BCunbwHDrgH/image.png

Thank you @ username. Your email address has been verified. Write down your username so you don't forget it!

**Comment by TimCliff** [comment] 2018-04-15 23:37
Duplicate of https://github.com/steemit/faucet/issues/242

**Closed** 2018-04-16 11:14 UTC
