### ISSUE TITLE
weird code displayed

### ISSUE THREAD

**Issue by sneak** [steemit/faucet#299] opened 2018-04-16 11:14 UTC
Got a support email which referenced the following link:

https://signup.steemit.com/create-account?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiY3JlYXRlX2FjY291bnQiLCJlbWFpbCI6ImppbmRqNzc3QG5hdmVyLmNvbSIsImlhdCI6MTUyMDg1MjEyMiwiZXhwIjoxNTIxNDU2OTIyfQ.g_7AsjtEhdq7nuh4ppBARMYJV4BbVFDvA-gAd2JrOuE

The token is invalid (WTF are the tokens so long anyway?! a uuid is more than sufficient to reference what's in the db) but it shows the following when clicked:

![image](https://user-images.githubusercontent.com/408977/38805997-e7efca6a-4145-11e8-8aa3-7233ce5e640e.png)

It shouldn't do that.

**Comment by jnordberg** [comment] 2018-04-16 11:39
Duplicate of #286

**Closed** 2018-04-16 11:39 UTC
