### ISSUE TITLE
Can't  receive sms confirmation 

### ISSUE THREAD

**Issue by Onlyforcryptoc** [steemit/faucet#380] opened 2018-07-01 19:00 UTC
Id  ONLYFORCRYPTOC@gmail.com trying to register but didn't  receive sms confirmation even after waiting for more than 24 hours

**Comment by TimCliff** [comment] 2018-07-01 20:13
This is a duplicate of https://github.com/steemit/faucet/issues/240.

There is currently no support if the SMS does not work with your carrier/area. You can try again later to see if it works. Some users have reported that a different SIM card has worked. If you are on a national 'do not call' list, that could be it too. If you are unable to get it to work with your phone, you may need to use one of the third-party signup options listed in the pinned messages of the steem.chat help channel (or the FAQ on steemit.com).

**Comment by TimCliff** [comment] 2018-08-16 16:33
This issue should be closed as dup.

**Closed** 2018-11-06 22:59 UTC
