### ISSUE TITLE
lots of users are reporting "invalid token"

### ISSUE THREAD

**Issue by sneak** [steemit/faucet#300] opened 2018-04-16 11:28 UTC
one such case: https://signup.steemit.com/create-account?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiY3JlYXRlX2FjY291bnQiLCJlbWFpbCI6Impvcmdlbi50YWV5bWFuc0BtZS5jb20iLCJpYXQiOjE1MjA4NjA0MTgsImV4cCI6MTUyMTQ2NTIxOH0.esSCZL2pn1LhdugC8q8LpZc-SQK54kosNUjkQ-lx9CY

**Comment by jnordberg** [comment] 2018-04-16 11:31
Duplicate of #246

**Closed** 2018-04-16 11:32 UTC
